import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/NavBar'
import About from '../components/About'
import styles from '../styles/Home.module.css'
import Projects from '../components/Projects'
import Main from '../components/Main'
import Contact from '../components/Contact'
import Footer from '../components/Footer'
import ScrollToTop from '../components/ScrollToTop'
import { useEffect, useState } from "react";

export default function Home(props) {
  const [scrollY, setScrollY] = useState(0);

  useEffect(() => {
    const options = { passive: true };
    const scroll = () => {
      const { scrollY } = window;
      setScrollY(scrollY);
    };
    document.addEventListener("scroll", scroll, options);
    // remove event
    () => document.removeEventListener("scroll", scroll, options);
  }, []);

  return (
    <div className={styles.container}>
      <Head>

        <title>RhysHalpinDev</title>
        {/*<meta name="viewport" content="width=device-width, initial-scale=1" />*/}
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />


      </Head>

      <Navbar theme={props.theme} setTheme={props.setTheme} />
      <Main />
      <About />
      <Projects />
      <Contact />
      <Footer />
      {scrollY > 750 ? <ScrollToTop /> : null}

    </div>
  )
}
