import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/NavBar'
import About from '../components/About'
import styles from '../styles/Home.module.css'
import Projects from '../components/Projects'
import Main from '../components/Main'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

export default function Home(props) {

  console.log(props)

  return (
    <div className={styles.container}>
      <Head>

        <title>RhysHalpinDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />


      </Head>
      <Navbar theme={props.theme} setTheme={props.setTheme} />
      <Main />
      <About />
      <Projects />
      <Contact />
      <Footer />
    </div>
  )
}
